FROM node:18.17.0 AS build

WORKDIR /app

COPY frontend/package*.json ./

RUN npm install

COPY frontend/ .

ENV REACT_APP_BACKEND_URL=/api

RUN npm run build

FROM nginx:alpine

COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]